Row type: make space for field names
Why: hiveTest for an internal MP fails like this:
```
Gradle suite > Gradle test > com.linkedin.YYYYYYYYYY.XXXXXX.ZZZZZZZ FAILED
    java.lang.AssertionError: UDF output does not match expected [{"field0":"class","field1":"exampleString"}] but found [{"classname":"class","data":"exampleString"}]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertEquals(Assert.java:123)
        at com.linkedin.transport.test.hive.HiveTester.assertFunctionCall(HiveTester.java:132)
        at com.linkedin.transport.test.spi.SqlStdTester.check(SqlStdTester.java:31)
        at com.linkedin.transport.test.spi.StdTester.check(StdTester.java:38)
        at com.linkedin.YYYYYYYYYY.XXXXXX.ZZZZZZZ(PPPPPPPPPP.java:24)
```

in this case, we couldn't match struct's key names because we fall back
to field0 when fieldnames aren't defined

Since modifying constructor would require a major version bump, I think
a chaining method would be good enough here

Test Plan: Tried to reproduce the test case my customer ran in one of
the examples. The example passed after my commit's is equals method was
implemented.